### ISSUE TITLE
Does the ANI implementation within NNPOps also consume 20x more memory with PBC?

### ISSUE THREAD

**Issue by JSLJ23** [openmm/NNPOps#106]
Hi `NNPOps` developers,

I was wondering how does the ANI AEV implementations within `NNPOps` handle the PBC in terms of memory consumption? Previously I was trying to run simulations with `torchANI` in `ASE` but setting the PBC conditions to true in `ASE` resulted in over a 20× requirement in memory which I assume was because of `torchANI` being required to evaluate the atoms in the 26 neighbouring PBC cells. Does `NNPOps` also face such a constraint when running within `OpenMM`? And are there any rough estimates on maximum system sizes (number of atoms) which can be run on a GPU with 24GB of VRAM?

Thank you for your time to address my queries.

Best regards,
Joshua Soon

**Comment by peastman** [comment]
With NNPOps, periodic boundary conditions should have no impact on memory use.

**Comment by JSLJ23** [comment]
Thank you for the prompt reply, that's good to know!
Just 2 more questions, for the PBC cells are they just copies of the central cell with some XYZ offset?
And the Neural Network's AEV is only evaluated in the central cell but not the PBC cells?

**Comment by peastman** [comment]
> For the PBC cells, are they just copies of the central cell with some XYZ offset?

Correct.

> And are the Neural Network's AEV only evaluated in the central cell but not the in PBC cells?

With periodic boundary conditions, every "atom" really represents an infinite grid of atoms repeating through space.  Each one of them has an identical environment, and therefore an identical AEV.

**Comment by JSLJ23** [comment]
Got it, thank you!
