### ISSUE TITLE
NNPOps installation/build missing dependencies (absent from environment.yml)

### ISSUE THREAD

**Issue by dominicrufa** [openmm/NNPOps#27]
Hi, I wasn't able to install and build the `NNPOPS` [here](https://github.com/openmm/NNPOps/tree/master/pytorch#build--install) as described, but i was able to install and see passing pytests with the attached env.txt
[nnpops_openmm_torch_env.txt](https://github.com/openmm/NNPOps/files/7144441/nnpops_openmm_torch_env.txt)
thanks to @ijpulidos. i seem to need `cudnn`, `cudatoolkit-dev`, and `gxx_linux-64=10.3.0` to `cmake` and install successfully (which i think is missing from the `environment.yml`)

To run [example](https://github.com/openmm/NNPOps/tree/master/pytorch#example) with `TorchForce`, do I need the conda-installable version of `torchani` or [this](https://github.com/raimis/torchani) version?

**Comment by ijpulidos** [comment]
Hi @raimis I think the process has improved a lot!! thanks for this, this is a great improvement.
In any case, I am getting the following error when I try the instructions (this is in the `make install` step):
```
❯ make install
[  7%] Building CXX object CMakeFiles/NNPOpsPyTorch.dir/src/ani/CpuANISymmetryFunctions.cpp.o
[ 14%] Building CUDA object CMakeFiles/NNPOpsPyTorch.dir/src/ani/CudaANISymmetryFunctions.cu.o
[ 21%] Building CXX object CMakeFiles/NNPOpsPyTorch.dir/src/pytorch/SymmetryFunctions.cpp.o
[ 28%] Building CXX object CMakeFiles/NNPOpsPyTorch.dir/src/schnet/CpuCFConv.cpp.o
[ 35%] Building CUDA object CMakeFiles/NNPOpsPyTorch.dir/src/schnet/CudaCFConv.cu.o
[ 42%] Linking CXX shared library libNNPOpsPyTorch.so
/home/ijpulidos/miniconda3/envs/nnpops/bin/../lib/gcc/x86_64-conda-linux-gnu/9.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lcudart_static
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/NNPOpsPyTorch.dir/build.make:178: libNNPOpsPyTorch.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:195: CMakeFiles/NNPOpsPyTorch.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
Any ideas why this may be happening? Thanks!

**Comment by raimis** [comment]
Can you post the configuration (i.e. `cmake`) output. It seems something is wrong with CUDA.

**Comment by raimis** [comment]
I have update the environment file (#56).

Note: `cudatoolkit-dev` is causing problems for CI, so it is not included.
