### ISSUE TITLE
Custom PyTorch operations

### ISSUE THREAD

**Issue by raimis** [openmm/NNPOps#3]
Requirements and progress of the custom operations for PyTorch.

Requirements:
- [x] ANI symmetry functions with adjustable parameters
- [x] Derivatives with respect to atomic coordinates
- [x] Compatible with TorchScript
- [x] CPU and GPU implementations
- [ ] Conda package

Relevant documentation:
- https://pytorch.org/tutorials/advanced/cpp_extension.html
- https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html

**Comment by raimis** [comment]
For us (@raimis, @stefdoerr @giadefa), this functionally is the highest priority in short term. In the past, I have worked a bit with the PyTorch internals and will be able to contribute. @peastman what do you think?

**Comment by peastman** [comment]
I have the first two of those done for CPU.  Next on my list is the CUDA version.

My current plan for this repository is that it will be source code only, a collection of mostly independent classes that people can directly incorporate into their own projects.  Do you want to start working on the PyTorch library?  We should consider exactly what we want that to be.  Perhaps a complete implementation of the potential that uses this library for the symmetry functions and standard PyTorch ops for the neural network part?

**Comment by raimis** [comment]
I'm talking just about the bindings to PyTorch, so the operations in this library can be used directly form PyTorch.

**Comment by peastman** [comment]
Sounds like a good first step.

**Comment by raimis** [comment]
Everything is completed here, except the conda package (#26).
