### ISSUE TITLE
GPU memory consumption of NNPOps

### ISSUE THREAD

**Issue by wiederm** [openmm/NNPOps#77]
I have seen increased GPU memory consumption using NNPOps compared to the original `torchani` implementation. Attached is a plot that shows the memory consumption of ANI-2x on the CUDA platform with `nnpops` and the `torchani` implementation for a watercluster test system. I am wondering if this is expected behavior or if I am doing something wrong? I am using the `openmm-8.0-beta` conda environment and `openmmml` to perform the benchmark watercluster calculations.

(The plot shows on the x-axis the number of atoms in the system and on the left y-axis the time it takes to execute a single energy evaluation and on the right y-axis the GPU memory footprint of the model. The dotted lines show the GPU memory. The labels are always `model/platform/implementation`)

![benchmarking](https://user-images.githubusercontent.com/31651017/212013666-6011d2aa-87c8-47b5-90b2-3b50a0896503.png)

**Comment by raimis** [comment]
Yes, it is expected. The `nnpops` implementation is trading memory for speed.

**Comment by wiederm** [comment]
Thanks for the clarification!
